### ISSUE TITLE
I turned this into a JSON API / web UI using my Datasette project

### ISSUE THREAD

**Issue by simonw** [vicenews/shot-by-cops#1]
https://vice-police-shootings.now.sh/vice-bc7c892/ViceNews_FullOISData

e.g. search for machete and get the results as JSON: https://vice-police-shootings.now.sh/vice-bc7c892/ViceNews_FullOISData.jsono?_search=machete

Here are notes on how I built this: https://gist.github.com/simonw/6785c842e6b0849aee3a9b1ef59d492e

**Comment by simonw** [comment]
Here's an example query showing the departments with the most shootings: https://vice-police-shootings.now.sh/vice-bc7c892?sql=select+ViceNews_FullOISData.Department%2C+Department.value%2C+count%28*%29+as+c+from+ViceNews_FullOISData+join+Department+on+ViceNews_FullOISData.Department+%3D+Department.id+group+by+ViceNews_FullOISData.Department+order+by+c+desc%3B

**Comment by atmccann** [comment]
Thanks for this! Going to close this though since it's not an issue.
