### ISSUE TITLE
Various Data Quality Issues

### ISSUE THREAD

**Issue by dkfurrow** [vicenews/shot-by-cops#3]
So, before I go through the points below, I'd like to say that it's commendable that Vice put its data out on Github for review.  All similar journalistic and academic projects should be this transparent.  

With that stated, I note the following:

> You may disagree with our methodology — so we’ve provided both standardized and original versions of our data from each department.

1. Code: *initial_data_processing.R* and *building_subject_database.r* are looking for the raw data files you mentioned, but **they aren't included in the repo**.  It is true that, in the case I was interested in, you point to raw files outside the repo.   *final_analysis.r* builds on the processing of those un-included raw data files...If I substitute the csv files in the repo for "vic" and "r" datasets (subject and incident data), I can replicate many of the results, but it errors on the age function. *graphics.r* picks up the final csv files, so that works for the few I tried.

2. There are #Ref entries in the data files...should adopt a consistent standard for NA's, those look like they were imported from a spreadsheet somehow.

3. The 'Fatal' column in the subject database has spaces in some of the fields, but not all...this should probably be cleaned up (found when I was trying to replicate your results).

4. There should be a clear identifier or identification method between incident and subject data...relates to further comments below.  I'd suggest a method like "Date"-"City"-"IncidentNumber"-"SubjectNumber", where the last is derived  from the "split" function on SubjectRace, SubjectGender, etc.   

5. City population doesn't look right.  CharlotteMecklenburg appears to have a sum of black, asian, hispanic, white of 1269k, but a population of only 948k.

6.  Big issue: ***Armed vs Unarmed Subjects***. There definitely seem to be some data quality problems there, at least as far as my review has gone.

**From the data description:**

>When possible, we read the narratives in these cases and categorized each incident by hand.

>In a handful of incidents, officers said people were armed with their “fists” — literally armed with their arms. We marked that as unarmed.

>Sometimes incidents involved multiple civilians, but police departments only included information about one weapon. In these cases, we assumed that every civilian involved was armed with that weapon.

>We also accepted the official police version of events as true, though such accounts have been disputed in the past.  

>The term “other” was used as a catch-all for additional weapons, from vehicles to rocks to walking sticks.

**My Review:** I matched Vice's totals of weapon status, by percentage, down to the decimal:

<table>
<tbody>
<tr><td>gun    </td><td style="text-align: right;">0.519347 </td></tr>
<tr><td>unarmed</td><td style="text-align: right;">0.200213 </td></tr>
<tr><td>knife  </td><td style="text-align: right;">0.0802272</td></tr>
<tr><td>U      </td><td style="text-align: right;">0.0777423</td></tr>
<tr><td>other  </td><td style="text-align: right;">0.0663827</td></tr>
<tr><td>replica</td><td style="text-align: right;">0.056088 </td></tr>
</tbody>
</table>

Those percentages are associated with the following raw numbers:

<table>
<thead>
<tr><th>       </th><th style="text-align: right;">  Houston</th><th style="text-align: right;">  All</th></tr>
</thead>
<tbody>
<tr><td>U      </td><td style="text-align: right;">        6</td><td style="text-align: right;">  219</td></tr>
<tr><td>gun    </td><td style="text-align: right;">      155</td><td style="text-align: right;"> 1463</td></tr>
<tr><td>knife  </td><td style="text-align: right;">       14</td><td style="text-align: right;">  226</td></tr>
<tr><td>other  </td><td style="text-align: right;">       30</td><td style="text-align: right;">  187</td></tr>
<tr><td>replica</td><td style="text-align: right;">       29</td><td style="text-align: right;">  158</td></tr>
<tr><td>unarmed</td><td style="text-align: right;">       79</td><td style="text-align: right;">  564</td></tr>
<tr><td>All    </td><td style="text-align: right;">      313</td><td style="text-align: right;"> 2817</td></tr>
</tbody>
</table>

Houston was my interest, and it has full narratives, so I reviewed each of them. I found 33 to be questionable in terms of armed status, using the definitions above found in the data description (note that narratives are repeated, as one would expect, because the subject database restates incidents which involve multiple suspects).  It is possible that many of the problematic entries below relate to this issue of aggregating multiple-subject incidents, but some of the issues I found involve incidents which don't have multiple subjects. Finally, one might quibble with my review for some of these, but most of these seem quite clear to me.  

<table>
<thead>
<tr><th style="text-align: right;">  Record</th><th>Date      </th><th>Weapon  </th><th>FullNarrative  </th></tr>
</thead>
<tbody>
<tr><td style="text-align: right;">    1401</td><td>8/9/2010  </td><td>unarmed </td><td>A suspicious person suspect was located.  He was found to be armed and
refused to drop his weapon after being confronted by the officer
forcing the officer to shoot at the suspect.                </td></tr>
<tr><td style="text-align: right;">    1412</td><td>11/30/2010</td><td>unarmed </td><td>An armed domestic violence suspect ran from the scene when the
officers arrived. The suspect shot at the officers multiple times as
they attempted to contain him within a confined area.  The suspect
raised his weapon to fire on the officers again when he shot multiple
times.                </td></tr>
<tr><td style="text-align: right;">    1496</td><td>9/30/2013 </td><td>unarmed </td><td>Suspect dives outside of a house through a window and refuses to
comply with officer's commands.  The suspect charges the officer with
a glass shard in hand.  The officer in fear for his life shoots the
suspect twice.  The suspect is hospitalized but expected to survive.                </td></tr>
<tr><td style="text-align: right;">    1507</td><td>2/27/2014 </td><td>unarmed </td><td>On-duty officer was informed that the suspect had stolen an item.  The
officer followed the suspect into the street and identified himself.
Suspect walked away, picked up a piece of lumber and swinging it at
officer in close range.  Fearing for his life, the officer discharged
his firearm and shot him in the arm.                </td></tr>
<tr><td style="text-align: right;">    3982</td><td>2/8/2010  </td><td>unarmed </td><td>Officer saw the suspects committing a burglary. He was attempting to
arrest them when one of the suspects shot the officer.                </td></tr>
<tr><td style="text-align: right;">    3991</td><td>2/24/2011 </td><td>unarmed </td><td>The officers were executing a narcotics search warrant when the
suspects fired at and shot one one of the officers.                </td></tr>
<tr><td style="text-align: right;">    3995</td><td>9/3/2011  </td><td>unarmed </td><td>The officer was handcuffing one suspect when he found a pistol on him.
A second suspect then drove his vehicle into the officers patrol car.
The suspect then exited the vehicle and ran at the officer with his
hand behind his back. The officer believed the suspect to be armed so
he was forced to shoot the suspect.                </td></tr>
<tr><td style="text-align: right;">    4010</td><td>1/12/2013 </td><td>unarmed </td><td>Three armed unknown suspects walked into an electronics store,
attempted to rob it, and were fired upon by an off-duty officer
working an extra job.                </td></tr>
<tr><td style="text-align: right;">    4011</td><td>1/12/2013 </td><td>unarmed </td><td>Three armed unknown suspects walked into an electronics store,
attempted to rob it, and were fired upon by an off-duty officer
working an extra job.                </td></tr>
<tr><td style="text-align: right;">    4012</td><td>1/12/2013 </td><td>unarmed </td><td>Three armed unknown suspects walked into an electronics store,
attempted to rob it, and were fired upon by an off-duty officer
working an extra job.                </td></tr>
<tr><td style="text-align: right;">    4017</td><td>4/6/2013  </td><td>unarmed </td><td>During a traffic stop, a HPD officer confronted a suspect that fled on
foot, jumped a fence, and brandished a handgun.  One of the officers
feared for his life and his partner's life, discharging his weapon.
No injuries were reported at the time of this incident and the
passenger was arrested for P.O.M.                </td></tr>
<tr><td style="text-align: right;">    4020</td><td>4/10/2013 </td><td>unarmed </td><td>Off duty officers working an extra job encountered suspicious males at
the parking lot.  Officers attempted to stop the vehicle and
investigate, but the driver pointed a pistol at one of the officers
and attempted to run them over.  Officers fired and missed the
suspects.                </td></tr>
<tr><td style="text-align: right;">    4021</td><td>4/10/2013 </td><td>unarmed </td><td>Off duty officers working an extra job encountered suspicious males at
the parking lot.  Officers attempted to stop the vehicle and
investigate, but the driver pointed a pistol at one of the officers
and attempted to run them over.  Officers fired and missed the
suspects.                </td></tr>
<tr><td style="text-align: right;">    4022</td><td>4/10/2013 </td><td>unarmed </td><td>Off duty officers working an extra job encountered suspicious males at
the parking lot.  Officers attempted to stop the vehicle and
investigate, but the driver pointed a pistol at one of the officers
and attempted to run them over.  Officers fired and missed the
suspects.                </td></tr>
<tr><td style="text-align: right;">    4028</td><td>6/2/2013  </td><td>unarmed </td><td>An HPD officer was chasing a stolen vehicle, suspect evaded, and one
of the suspects pointed a rifle at the officer.  The officer, in fear
of his life, shot and missed the suspect.  Suspect arrested and
charged.                </td></tr>
<tr><td style="text-align: right;">    4029</td><td>6/2/2013  </td><td>unarmed </td><td>An HPD officer was chasing a stolen vehicle, suspect evaded, and one
of the suspects pointed a rifle at the officer.  The officer, in fear
of his life, shot and missed the suspect.  Suspect arrested and
charged.                </td></tr>
<tr><td style="text-align: right;">    4030</td><td>6/2/2013  </td><td>unarmed </td><td>An HPD officer was chasing a stolen vehicle, suspect evaded, and one
of the suspects pointed a rifle at the officer.  The officer, in fear
of his life, shot and missed the suspect.  Suspect arrested and
charged.                </td></tr>
<tr><td style="text-align: right;">    4033</td><td>9/9/2013  </td><td>unarmed </td><td>Officers conducted a traffic stop.  The driver ignored officers
commands to exit the vehicle, drove off, and fired upon officers
running to their patrol cars.  Suspect fired upon officers again while
evading, exited car, fired again, and was ultimately killed by
officers in fear of their lives.                </td></tr>
<tr><td style="text-align: right;">    4035</td><td>9/13/2013 </td><td>unarmed </td><td>Officers were investigating BMVs, one suspect attempted to evade
arrest by jumping into the suspect's vehicle and at a high rate of
speed left the road way crashing the stolen vehicle. The suspect fled
on foot, pointing his weapon at pursing officers. Officers fired at
and wounded the suspect. No HPD officers were injured.                </td></tr>
<tr><td style="text-align: right;">    4036</td><td>9/13/2013 </td><td>unarmed </td><td>Officers were investigating BMVs, one suspect attempted to evade
arrest by jumping into the suspect's vehicle and at a high rate of
speed left the road way crashing the stolen vehicle. The suspect fled
on foot, pointing his weapon at pursing officers. Officers fired at
and wounded the suspect. No HPD officers were injured.                </td></tr>
<tr><td style="text-align: right;">    4037</td><td>9/13/2013 </td><td>unarmed </td><td>Officers were investigating BMVs, one suspect attempted to evade
arrest by jumping into the suspect's vehicle and at a high rate of
speed left the road way crashing the stolen vehicle. The suspect fled
on foot, pointing his weapon at pursing officers. Officers fired at
and wounded the suspect. No HPD officers were injured.                </td></tr>
<tr><td style="text-align: right;">    4049</td><td>2/14/2014 </td><td>unarmed </td><td>On duty HPD officer responding to hold-up alarm encountered three
suspects exiting the business. One of the fleeing suspect pointed a
weapon at the officer. The officer discharged his weapon at the
suspect but missed. All three suspects were apprehended and the stolen
money and property were recovered.  One suspect received minor
injuries from a K9.                </td></tr>
<tr><td style="text-align: right;">    4050</td><td>2/14/2014 </td><td>unarmed </td><td>On duty HPD officer responding to hold-up alarm encountered three
suspects exiting the business. One of the fleeing suspect pointed a
weapon at the officer. The officer discharged his weapon at the
suspect but missed. All three suspects were apprehended and the stolen
money and property were recovered.  One suspect received minor
injuries from a K9.                </td></tr>
<tr><td style="text-align: right;">    4059</td><td>5/5/2014  </td><td>unarmed </td><td>Suspect fled from the officer. Suspect was attempting to jump a fence
when the officer caught up to him. The suspect turned with a weapon in
his hand pointed toward the officer.  THe officer discharged his
weapon striking and killing the suspect.                </td></tr>
<tr><td style="text-align: right;">    4070</td><td>1/16/2015 </td><td>unarmed </td><td>An HPD officer working an extra job in uniform at a convenient store
saw three black males enter with a shotgun pointed inside the store.
The officer fired at the suspects who again pointed the weapon at the
pursuing officer.  The officer again shot and injured a suspect.  HCSO
worked the shooting.                </td></tr>
<tr><td style="text-align: right;">    4071</td><td>1/16/2015 </td><td>unarmed </td><td>An HPD officer working an extra job in uniform at a convenient store
saw three black males enter with a shotgun pointed inside the store.
The officer fired at the suspects who again pointed the weapon at the
pursuing officer.  The officer again shot and injured a suspect.  HCSO
worked the shooting.                </td></tr>
<tr><td style="text-align: right;">    4073</td><td>2/10/2015 </td><td>unarmed </td><td>An HPD officer responded to a home invasion.  When the officer
encountered the suspect, the suspect fired and missed at the officer.
The officer returned fire and also missed the suspect.  A total of
three suspects were involved.  The shooter was arrested and two others
remains at large.                </td></tr>
<tr><td style="text-align: right;">    4074</td><td>2/10/2015 </td><td>unarmed </td><td>An HPD officer responded to a home invasion.  When the officer
encountered the suspect, the suspect fired and missed at the officer.
The officer returned fire and also missed the suspect.  A total of
three suspects were involved.  The shooter was arrested and two others
remains at large.                </td></tr>
<tr><td style="text-align: right;">    4080</td><td>7/7/2015  </td><td>unarmed </td><td>Three suspects fled in a vehicle, they pointed weapons at persuing
officers. In fear of his life, an officer discharged his duty weapon
multiple times and struck the suspects, killing one, injuring two.                </td></tr>
<tr><td style="text-align: right;">    4082</td><td>8/21/2015 </td><td>unarmed </td><td>Officer working and extra job handling a distrubance between two males
in the parking lot. A vehicle drove by the location and one occupant
discharged a round towards the officer. The officer returned fire and
struck the vehicle. The vehicle fled the scene. There were no injuries
to the officer.                </td></tr>
<tr><td style="text-align: right;">    4086</td><td>10/15/2015</td><td>unarmed </td><td>DPS  and NW Patrol officers observed three suspects enter a cash store
and attempt to rob it.  DPS and NW officeres discharged their weapons
striking the suspects when they ran at the officers with guns drawn.
One suspect was killed, another wounded, and a third was arrested. No
officers were injured.                </td></tr>
<tr><td style="text-align: right;">    4091</td><td>12/29/2015</td><td>unarmed </td><td>Off duty officer in plain clothes was approached by two suspects while
in his vehicle.  One suspect pointed a gun at the officer and demanded
everything.  The suspect then pulled the trigger but the weapon
misfired.  The officer drew his firearm and shot the suspect.  Both
suspects fled and were later apprehended.                </td></tr>
<tr><td style="text-align: right;">    4094</td><td>1/19/2016 </td><td>unarmed </td><td>"Northeast Officer was on a suspicious person call when the suspects
shot at him. The officer was transported to Memorial Hermann hospital
with a gunshot wound to the left arm. He is reported to be in stable
condition. Two suspects were apprehended later by HPD officers. "                </td></tr>
</tbody>
</table>

**Comment by rkarthur** [comment]
Hey dkfurrow,

I appreciate your thorough review of our data. I’ll respond to each of your issues point by point.
1) That’s right, those scripts are used to generate the final incident and subject-level databases uploaded to the Github. If you wish to generate those databases yourself, you can download the data files for each city and place them in the directory where you run the initial_data_processing.R script. And you’re right that vic refers to the subject-level data and r to the incident-level data.
2) We have tried to correct #Ref errors--these were introduced when we uploaded our data to Google sheets. If you tell me which rows you found those in, I’m happy to fix them.
3) This issue did not affect our analysis or results, but I can see how it would be inconvenient. You can resolve this easily in R with the following line: 
gsub(“ “, “”, data$Fatal)
4) We debated including such an identifier but decided against it. You can easily build one yourself in the manner you just described.
5) The four columns after total population need not match the total population, since they do not exhaust all possible racial groupings. Furthermore, ethnic groups can be overlapping: a person might consider themselves both black and Hispanic, adding one to each column. We believe this explains most of the discrepancies, but there is in fact an error in Charlotte-Mecklenburg: the black population there is too high. This error did not affect the content of the article but we will upload a corrected csv soon.
6) We investigated some of the incidents you listed. Most refer to cases with multiple subjects, only one of whom had a weapon. In these cases, a subject who wasn’t armed would be listed as unarmed even if an accompanying subject who fired at the officer did have a firearm.

The Houston Police Department supplied both a brief narrative and, separately, a field listing whether each subject had a weapon (and if so, what weapon they had). This raw data is available here: 
http://houstontx.gov/police/ois/index.htm

In another case, the Houston Police Department lists a subject as unarmed even though the narrative states that they shot at the police officer. When available, we used the “weapon” field to inform our analysis, not the narrative. And in most cases, we didn’t attempt to resolve internal contradictions like this.

Finally, as we noted on our methodology page, there are some cases that we believe fall into the category of judgment calls.

You are welcome to recode our data using your own judgment or your reading of the narratives, or you may attempt to resolve those internal inconsistencies within the Houston Police Department’s records. However, after having reviewed these incidents, we stand by our initial coding.

Again, thank you for looking over our article and data, and please let me know if you find any other inconsistencies.
-Rob

**Comment by atmccann** [comment]
@dkfurrow the Charlotte-Mecklenburg population data has been corrected. Thank you for flagging!

**Comment by dkfurrow** [comment]
Thanks @atmccann.  I updated to get the csv file, discovered that, at commit 2000995761841b0a8ef778a77ddb588d882a32a5 on 12/20, looks like a bunch of columns, notably `[year, month, day, Fixed Date, b, l, w, a, tr, AvgAge, VA, F, nshots, sit, other, replica, knife, weapon] were dropped from incident_data.csv...I don't know if that was intentional, looks as if that data results from  building_subject_data.r.  I'm guessing that script wasn't re-run fully at the time? I'd suggest those columns are pretty important for anyone wishing to replicate your results.

@rkarthur  thanks for the explanation and response.  It's your article, and your repo--as I noted, I appreciate your sharing the data in such a transparent way. I guess each of us can look through the narratives and decide for himself/herself.

**Comment by atmccann** [comment]
@dkfurrow you're right, those columns were somehow dropped in the last update. We added them back in this morning, thanks again for being so thorough in checking this data.
